# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ppgit}
  s.version = "0.7.4"
  s.authors = ["Alain Ravet"]
  s.date = %q{2010-11-04}
  s.summary     = %q{git users' pairs switcher}
  s.description = s.summary
  s.email = %q{alainravet@gmail.com}
  s.executables = ["git-pp", "ppgit"]
  s.files         = `git ls-files`.split("\n") #.reject { |name| name.include?('examples') }
  s.test_files    = `git ls-files -- {spec}/*`.split("\n")
  s.homepage = %q{http://github.com/alainravet/ppgit}
  s.require_paths = ["lib"]

  s.files         = `git ls-files`.split("\n")
  s.test_files    = `git ls-files -- {spec}/*`.split("\n")

  s.add_development_dependency "rspec"

  s.license       = 'MIT'
end

